{
 "title": "Control Plane Logs",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "query": "consul" },
   { "name": "app", "query": { "query": "label_values(app)" } },
   { "name": "searchable_pattern", "label": "Search (case insensitive)" }
  ]
 },
 "panels": [
  {
   "title": "Total logs",
   "type": "stat",
   "description": "Total  Count of log lines in the specified time range",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=~\"$namespace\", app=\"$app\"} [$__interval]))"
    }
   ]
  },
  {
   "title": "Total logs containing \"$searchable_pattern\"",
   "type": "stat",
   "description": "Total count of logs containing the search filter term in the specified time range",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=~\"$namespace\", app=\"$app\"} |~ `(?i)(?i)$searchable_pattern` [$__interval]))"
    }
   ]
  },
  {
   "title": "Percentage of logs containing \"$searchable_pattern\"",
   "type": "stat",
   "description": "Percentage of logs containing the search filter term in the specified time range",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(count_over_time({namespace=~\"$namespace\", app=\"$app\"} |~ `(?i)(?i)$searchable_pattern` [$__interval])) * 100) / sum(count_over_time({namespace=~\"$namespace\", app=\"$app\"} [$__interval]))"
    }
   ]
  },
  {
   "title": "Method Distribution",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(method) (count_over_time({namespace=\"$namespace\", app=\"$app\"} | logfmt | method != `` | __error__=`` [$__range]))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Log Type Distribution",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(_TRACE_) (count_over_time({app=\"$app\", namespace=\"$namespace\"} |= `[TRACE]` | logfmt | __error__=`` [$__range]))",
     "legendFormat": "TRACE"
    },
    {
     "expr": "sum by(_DEBUG_) (count_over_time({app=\"$app\", namespace=\"$namespace\"} |= `[DEBUG]` | logfmt | __error__=`` [$__range]))",
     "legendFormat": "DEBUG"
    },
    {
     "expr": "sum by(_INFO_) (count_over_time({app=\"$app\", namespace=\"$namespace\"} |= `[INFO]` | logfmt | __error__=`` [$__range]))",
     "legendFormat": "INFO"
    },
    {
     "expr": "sum by(_ERROR_) (count_over_time({app=\"$app\", namespace=\"$namespace\"} |= `[ERROR]` | logfmt | __error__=`` [$__range]))",
     "legendFormat": "ERROR"
    }
   ]
  },
  {
   "title": "Log Source Distribution",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(pod) (count_over_time({app=\"$app\", namespace=\"$namespace\"} | logfmt | pod != `` | __error__=`` [$__range]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "RPC Server Call Request Type Distribution",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(request_type) (count_over_time({namespace=\"$namespace\", app=\"$app\"} | logfmt | request_type != `` | __error__=`` [$__range]))",
     "legendFormat": "{{request_type}}"
    }
   ]
  },
  {
   "title": "RPC Server Call Success/Error Ratio",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(errored) (count_over_time({app=\"$app\", namespace=\"$namespace\"} | logfmt | __error__=`` | errored!=\"\" [$__range]))",
     "legendFormat": "Error: {{errored}}"
    }
   ]
  },
  {
   "title": "RPC Server Call Blocking Distribution",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(blocking) (count_over_time({app=\"$app\", namespace=\"$namespace\"} | logfmt | __error__=`` | blocking != `` [$__range]))",
     "legendFormat": "{{blocking}}"
    }
   ]
  },
  {
   "title": "Logs containing \"$searchable_pattern\" over [$__interval]",
   "type": "logs",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "{namespace=\"$namespace\", app=\"$app\", component=\"server\"} |= `` | logfmt |~ `(?i)$searchable_pattern`"
    }
   ]
  }
 ]
}